-- 2021년에 가입 => JOINED의 YEAR 값이 2021
-- 중복 회원 ID 제거하여 COUNT => DISTINCT
SELECT YEAR(O.SALES_DATE) YEAR, MONTH(O.SALES_DATE) MONTH, 
COUNT(DISTINCT U.USER_ID) PUCHASED_USERS, -- 상품을 구매한 회원수
ROUND(COUNT(DISTINCT U.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) PUCHASED_RATIO -- ROUND(상품 구매 회원 수 / 전체 회원 수, 1)
FROM ONLINE_SALE O JOIN USER_INFO U ON O.USER_ID = U.USER_ID
WHERE YEAR(U.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;

